

<template>
    <div class="benefits-info" >
        <h1 class="benefits-font">Encourage new users to join TRE networks, they become your downline, and you can earn commissions generated by those individuals. Your downline also recruits new downlines into the company, create a hierarchy of partnership, with those at the top of the organization earning commissions on the downlines beneath them.</h1>
    </div>
</template>
<script>
export default {
    name: "BenefitsInfo", 
    
};

</script>

<style>
.benefits-info{
background-color: #58c06e;
border-radius: 130px;
opacity: 1;
height: fit-content;
width: 80vw;
margin-left: 8vw;
resize: both;

}
.benefits-font{
    text-align: left;
letter-spacing: 0px;
color: #FFFFFF;
opacity: 1;
/* font-size: 2vh; */
margin-left: 1.5vw;
font: normal normal normal 3vh Segoe UI;
}

</style>